export const LOGOS = {
  calendar: { src: "Calendar.png", link: "" },
  chat: { src: "Chat.png", link: "" },
  classroom: { src: "CLassroom.png", link: "" },
  cloud: { src: "Cloud.png", link: "" },
  contacts: { src: "Contacts.png", link: "" },
  docs: { src: "Docs.png", link: "" },
  drive: { src: "Drive.png", link: "" },
  earth: { src: "Earth.png", link: "" },
  firebase: { src: "Firebase.png", link: "" },
  forms: { src: "Forms.png", link: "" },
  gmail: { src: "Gmail.png", link: "" },
  maps: { src: "Maps.png", link: "" },
  meet: { src: "Meet.png", link: "" },
  news: { src: "News.png", link: "" },
  photos: { src: "Photos.png", link: "" },
  play: { src: "Play.png", link: "" },
  search: { src: "Search.png", link: "" },
  sheets: { src: "Sheets.png", link: "" },
  shopping: { src: "Shopping.png", link: "" },
  slides: { src: "Slides.png", link: "" },
  translate: { src: "Translate.png", link: "" },
  youtube: { src: "Youtube.png", link: "" },
};
Object.freeze(LOGOS);
